{"timestamp": "2025-09-18T15:05:47.426274", "level": "ERROR", "module": "logger_manager", "function": "error", "line": 250, "message": "Error occurred: OperationalError: (2003, \"Can't connect to MySQL server on '[REDACTED]'\")", "taskName": "Task-1", "context": {"method": "initialize_database"}, "asctime": "2025-09-18 18:35:47"}
{"timestamp": "2025-09-18T15:05:47.441411", "level": "ERROR", "module": "logger_manager", "function": "log_error_with_context", "line": 281, "message": "Error occurred: OperationalError: (2003, \"Can't connect to MySQL server on '[REDACTED]'\")", "taskName": "Task-1", "context": {"phase": "initialization"}, "asctime": "2025-09-18 18:35:47"}
{"timestamp": "2025-09-18T15:06:13.953774", "level": "ERROR", "module": "logger_manager", "function": "log_error_with_context", "line": 281, "message": "Error occurred: ConnectionError: Error 22 connecting to [REDACTED]:6379. The remote computer refused the network connection.", "taskName": "Task-1", "context": {"operation": "redis_initialize"}, "asctime": "2025-09-18 18:36:13"}
